apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend-config
  labels:
    {{- include "inventory-app.backend.labels" . | nindent 4 }}
data:
  flask-env: {{ .Values.backend.config.flaskEnv | quote }}
  app-name: {{ .Values.backend.config.appName | quote }}
  postgres-host: {{ include "inventory-app.fullname" . }}-postgresql
  postgres-db: {{ .Values.postgresql.database.name | quote }}