{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend
  labels:
    {{- include "inventory-app.backend.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend-role
  labels:
    {{- include "inventory-app.backend.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend-rolebinding
  labels:
    {{- include "inventory-app.backend.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "inventory-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "inventory-app.fullname" . }}-backend-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}