apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend-secret
  labels:
    {{- include "inventory-app.backend.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ "inventory_user" | b64enc }}
  postgres-password: {{ "inventory_password" | b64enc }}