apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-app.fullname" . }}-postgresql-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  01-init.sql: |
    -- Create products table
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      price DECIMAL(10,2),
      quantity INTEGER DEFAULT 0,
      discontinued BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Insert sample data
    INSERT INTO products (name, description, price, quantity, discontinued) VALUES
    ('Laptop', 'High-performance laptop', 999.99, 50, FALSE),
    ('Mouse', 'Wireless mouse', 29.99, 100, FALSE),
    ('Keyboard', 'Mechanical keyboard', 89.99, 75, FALSE),
    ('Monitor', '27-inch 4K monitor', 299.99, 30, FALSE),
    ('Old Phone', 'Discontinued phone model', 199.99, 5, TRUE);