apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-app.fullname" . }}-postgresql-secret
  labels:
    {{- include "inventory-app.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ "inventory_password" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-app.fullname" . }}-postgresql-init
  labels:
    {{- include "inventory-app.postgresql.labels" . | nindent 4 }}
data:
  01-init.sql: |
    -- Create database if it doesn't exist
    SELECT 'CREATE DATABASE inventory' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'inventory')\gexec
    
    -- Connect to inventory database
    \c inventory;
    
    -- Create products table if it doesn't exist
    CREATE TABLE IF NOT EXISTS products (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        quantity INTEGER NOT NULL DEFAULT 0,
        discontinued BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Insert sample data
    INSERT INTO products (name, quantity, discontinued) VALUES 
    ('Sample Product 1', 100, false),
    ('Sample Product 2', 50, false),
    ('Discontinued Product', 0, true)
    ON CONFLICT DO NOTHING;