apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-app.fullname" . }}-pgadmin-secret
  labels:
    {{- include "inventory-app.pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  pgadmin-email: {{ "admin@example.com" | b64enc }}
  pgadmin-password: {{ "pgadmin_password" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-app.fullname" . }}-pgadmin-config
  labels:
    {{- include "inventory-app.pgadmin.labels" . | nindent 4 }}
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Inventory PostgreSQL",
          "Group": "Servers",
          "Host": "{{ include "inventory-app.fullname" . }}-postgresql",
          "Port": 5432,
          "MaintenanceDB": "inventory",
          "Username": "inventory_user",
          "SSLMode": "prefer",
          "PassFile": "/tmp/pgpass"
        }
      }
    }