apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-app.fullname" . }}-pgadmin
  labels:
    {{- include "inventory-app.pgadmin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgadmin.service.type }}
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inventory-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin