apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "inventory-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "inventory-app.fullname" . }}-backend-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inventory-app.fullname" . }}-cronjob-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "inventory-app.fullname" . }}-cronjob
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "inventory-app.fullname" . }}-cronjob-role
  apiGroup: rbac.authorization.k8s.io