apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inventory-app.fullname" . }}-backend-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inventory-app.fullname" . }}-cronjob-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inventory-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
