{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inventory-app.fullname" . }}-frontend
  labels:
    {{- include "inventory-app.frontend.labels" . | nindent 4 }}
{{- end }}